### ISSUE TITLE
Add Some CPP Algorithm

### ISSUE THREAD

**Issue by gvpHactober** [gvpHactober/HactoberfestAccepted#1]

**Comment by gvpHactober** [comment]
Add here most common algorithms used in c/c++

**Comment by shin-iji** [comment]
Hello, can I do this?

**Comment by Sajal193** [comment]
Hi @gvpHactober . Can I work on this, I do programming in C++.

**Comment by gvpHactober** [comment]
go ahead @shin-iji @Sajal193
