### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by gvpHactober** [gvpHactober/HactoberfestAccepted#12]
**Create a TicTacToe game with HTML,,CSS,,JS**

**Comment by AravindHari** [comment]
Hey, @gvpHactober I can do this

**Comment by shrishtickling** [comment]
hi! I would like to do this. Could you please assign it to me?

**Comment by gvpHactober** [comment]
Go Ahead @AravindHari & @shrishtickling Show somw creativity
